### ISSUE TITLE
coroutine 'Page.exposeFunction.<locals>._evaluate' was never awaited

### ISSUE THREAD

**Issue by Melodi17** [shivamsn97/pymessages#1]
Keep getting this error when running the first example:
Note that I had to modify some of the library code since the ids have changed:
```python
# Line 106 of client.py
await self.page.waitForSelector('#mat-mdc-slide-toggle-1-button')
        await self.page.evaluate("""() => {
            const checkbox = document.querySelector('#mat-mdc-slide-toggle-1-button')
            checkbox.click() 
        }
        """) #remember me button
```

```
Traceback (most recent call last):
  File "C:\Users\melod\source\python\test_script.py", line 23, in <module>
    client.launch()
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymessages\client.py", line 43, in launch
    self.loop.run_until_complete(self._launch(self.options))
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymessages\client.py", line 114, in _launch
    await self._attachQrReader()
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymessages\client.py", line 75, in _attachQrReader
    await self.page.exposeFunction('onQrChange', _func_to_expose)
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyppeteer\page.py", line 610, in exposeFunction
    await asyncio.wait([_evaluate(frame, expression) for frame in self.frames])
  File "C:\Users\melod\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'Page.exposeFunction.<locals>._evaluate' was never awaited
```

**Comment by shivamsn97** [comment]
I will have a look into it.
